# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/hreinking/Dropbox (LSST)/workspace/lsst/gpva/ui/main.ui',
# licensing of '/Users/hreinking/Dropbox (LSST)/workspace/lsst/gpva/ui/main.ui' applies.
#
# Created: Mon Sep  9 12:12:12 2019
#      by: pyside2-uic  running on PySide2 5.12.3
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(691, 693)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(0, 370, 691, 221))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 689, 219))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.output = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        self.output.setGeometry(QtCore.QRect(10, 0, 671, 211))
        self.output.setObjectName("output")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(260, 70, 191, 31))
        self.label_5.setMaximumSize(QtCore.QSize(311, 16777215))
        self.label_5.setObjectName("label_5")
        self.all = QtWidgets.QCheckBox(self.centralwidget)
        self.all.setGeometry(QtCore.QRect(640, 30, 41, 31))
        self.all.setObjectName("all")
        self.server_list = QtWidgets.QComboBox(self.centralwidget)
        self.server_list.setGeometry(QtCore.QRect(530, 10, 151, 21))
        self.server_list.setObjectName("server_list")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 10, 29, 21))
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(210, 10, 74, 21))
        self.label_6.setObjectName("label_6")
        self.username = QtWidgets.QLineEdit(self.centralwidget)
        self.username.setGeometry(QtCore.QRect(60, 10, 131, 21))
        self.username.setText("")
        self.username.setObjectName("username")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(490, 10, 40, 20))
        self.label_2.setObjectName("label_2")
        self.password = QtWidgets.QLineEdit(self.centralwidget)
        self.password.setGeometry(QtCore.QRect(270, 10, 201, 21))
        self.password.setText("")
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setObjectName("password")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea_2.setGeometry(QtCore.QRect(0, 110, 691, 181))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 689, 179))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.argument = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.argument.setGeometry(QtCore.QRect(10, 0, 671, 171))
        self.argument.setObjectName("argument")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.send = QtWidgets.QPushButton(self.centralwidget)
        self.send.setGeometry(QtCore.QRect(245, 290, 96, 32))
        self.send.setObjectName("send")
        self.clear = QtWidgets.QPushButton(self.centralwidget)
        self.clear.setGeometry(QtCore.QRect(343, 290, 95, 32))
        self.clear.setObjectName("clear")
        self.exit = QtWidgets.QPushButton(self.centralwidget)
        self.exit.setGeometry(QtCore.QRect(590, 600, 96, 32))
        self.exit.setObjectName("exit")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(330, 340, 51, 21))
        self.label_7.setMaximumSize(QtCore.QSize(311, 16777215))
        self.label_7.setObjectName("label_7")
        self.reloadServers = QtWidgets.QPushButton(self.centralwidget)
        self.reloadServers.setGeometry(QtCore.QRect(530, 30, 71, 31))
        self.reloadServers.setObjectName("reloadServers")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar()
        self.menubar.setGeometry(QtCore.QRect(0, 0, 691, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionBackup = QtWidgets.QAction(MainWindow)
        self.actionBackup.setObjectName("actionBackup")
        self.actiontest = QtWidgets.QAction(MainWindow)
        self.actiontest.setObjectName("actiontest")
        self.actionNotes = QtWidgets.QAction(MainWindow)
        self.actionNotes.setObjectName("actionNotes")
        self.actionEditServer = QtWidgets.QAction(MainWindow)
        self.actionEditServer.setObjectName("actionEditServer")
        self.actionReloadServerList = QtWidgets.QAction(MainWindow)
        self.actionReloadServerList.setObjectName("actionReloadServerList")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionBackup)
        self.menuFile.addAction(self.actionClose)
        self.menuAbout.addAction(self.actionNotes)
        self.menuEdit.addAction(self.actionEditServer)
        self.menuEdit.addAction(self.actionReloadServerList)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "GPVA", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("MainWindow", "Commands (type one per line)", None, -1))
        self.all.setText(QtWidgets.QApplication.translate("MainWindow", "All", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("MainWindow", "User", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("MainWindow", "Password", None, -1))
        self.username.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "Remote Username", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "Server", None, -1))
        self.password.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "If no ssh keys, type a Password", None, -1))
        self.send.setText(QtWidgets.QApplication.translate("MainWindow", "Send", None, -1))
        self.send.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Return", None, -1))
        self.clear.setText(QtWidgets.QApplication.translate("MainWindow", "Clear", None, -1))
        self.exit.setText(QtWidgets.QApplication.translate("MainWindow", "Exit", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("MainWindow", "Output", None, -1))
        self.reloadServers.setText(QtWidgets.QApplication.translate("MainWindow", "Reload", None, -1))
        self.menuFile.setTitle(QtWidgets.QApplication.translate("MainWindow", "File", None, -1))
        self.menuAbout.setTitle(QtWidgets.QApplication.translate("MainWindow", "About", None, -1))
        self.menuEdit.setTitle(QtWidgets.QApplication.translate("MainWindow", "Edit", None, -1))
        self.actionOpen.setText(QtWidgets.QApplication.translate("MainWindow", "Open", None, -1))
        self.actionClose.setText(QtWidgets.QApplication.translate("MainWindow", "Close", None, -1))
        self.actionSave.setText(QtWidgets.QApplication.translate("MainWindow", "Save", None, -1))
        self.actionAbout.setText(QtWidgets.QApplication.translate("MainWindow", "About", None, -1))
        self.actionBackup.setText(QtWidgets.QApplication.translate("MainWindow", "Backup", None, -1))
        self.actiontest.setText(QtWidgets.QApplication.translate("MainWindow", "test", None, -1))
        self.actionNotes.setText(QtWidgets.QApplication.translate("MainWindow", "Notes", None, -1))
        self.actionEditServer.setText(QtWidgets.QApplication.translate("MainWindow", "Edit Server List", None, -1))
        self.actionReloadServerList.setText(QtWidgets.QApplication.translate("MainWindow", "Reload Server List", None, -1))

